name: Deploy to S3

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change to your S3 bucket's region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://deathbycoconut.band --delete --exclude ".git/*"

      # OPTIONAL: Invalidate CloudFront cache (if using a distribution)
      - name: Invalidate CloudFront cache
        if: ${{ secrets.DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            paths "/*"
